[project]
name = "gurobi-model-runner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gurobipy>=13.0.0",
    "openpyxl>=3.1.5",
    "pandas>=2.3.3",
]
